### ISSUE TITLE
/api/v1/generate not working

### ISSUE THREAD

**Issue by ashwwwin** [ashleykleynhans/oobabooga-legacy-api-extension#1]
I have enabled `api` in `Available extensions` and `listen` in `Boolean command-line flags` on RunPod but, still can't get any of the /api/v1/* links to work.

It returns `{"detail":"Not Found"}`

**Comment by ashleykleynhans** [comment]
@ashwwwin Which template ate you using?  Not sure what you mean by "Boolean command-line flags".

**Comment by ashwwwin** [comment]
@ashleykleynhans I'm using TheBloke Local LLMs One-Click UI and API (thebloke/cuda11.8.0-ubuntu22.04-oneclick:latest)
<img width="630" alt="Screenshot 2023-11-16 at 00 48 01" src="https://github.com/ashleykleynhans/oobabooga-legacy-api-extension/assets/73720705/743623cd-8df3-4dc2-828d-a5692f90d651">

**Comment by ashleykleynhans** [comment]
`api` should also be checked I believe, this is how my command line arguments look:

```
--listen --api --listen-port 3001 --api-port 5001 --api-blocking-port 6050 --api-streaming-port 6055 --extensions api
```

* Web UI on port 3001
* OpenAI API on port 5001
* Legacy REST API on port 6050
* Legacy WebSockets API on port 6055.

You can set command line arguments with the `UI_ARGS` environment variable on the template.

**Comment by ashleykleynhans** [comment]
You are also welcome to use [my template](https://runpod.io/gsc?template=el5m58e1to&ref=2xxro4sy) that already has the legacy API preinstalled and the ports added to the pod.

**Comment by ashwwwin** [comment]
`--listen --api --listen-port 3001 --api-port 5001 --api-blocking-port 6050 --api-streaming-port 6055 --extensions api`

This solved it, thank you so much!

Incase anyone gets stuck w `thebloke/cuda11.8.0-ubuntu22.04-oneclick:latest`, here's what I did to get it running after installing the extension:

1. Connect to the web terminal / ssh 
2. vim /workspace/run-text*
3. Change line 6 to `ARGS=("$@" --listen --api --listen-port 7860 --api-port 5000 --api-blocking-port 6050 --api-streaming-port 6055 --extensions api)`
4. Restart the pod

**Comment by ashwwwin** [comment]
`--listen --api --listen-port 3001 --api-port 5001 --api-blocking-port 6050 --api-streaming-port 6055 --extensions api`

This solved it, thank you so much!

Incase anyone gets stuck w `thebloke/cuda11.8.0-ubuntu22.04-oneclick:latest`, here's what I did to get it running after installing the extension:

1. Connect to the web terminal / ssh 
2. vim /workspace/run-text*
3. Change line 6 to `ARGS=("$@" --listen --api --listen-port 7860 --api-port 5000 --api-blocking-port 6050 --api-streaming-port 6055 --extensions api)`
4. Restart the pod

**Comment by ashleykleynhans** [comment]
@ashwwwin Thanks for this, I've updated the README with instructions for installing on TheBloke's RunPod template.
